version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3500:3500"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


volumes:
  data:
  logs: